title: Nathalia Góes - UX Designer
author: Nathalia Goes
email: nathy.glima@gmail.com
description: > #
  Aqui falo um pouco sobre minha trajetória profissional ao longo dos mais de 8 anos de
  convivência com produtos digitais.

baseurl: /nathaliagoes

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore

# Date format for posts
# refer to http://shopify.github.io/liquid/filters/date/ if you
# want to customize this
date_format: "%b %-d, %Y"

# generate social links in footer
linkedin: nathaliagoes https://www.linkedin.com/in/nathaliagoes/

saas:
  saas_dir: _saas